fix: fix form item width
alauda/alauda-ui pull request #190
Opened 2021-11-05 07:07 UTC by yinshuxun

2021-11-05 07:08 UTC, yinshuxun commented
如果元素上有flex:1 优先级会比width高，会不生效，所以设置max-widht

2021-11-08 08:12 UTC, JounQin approved these changes

2021-11-08 08:12 UTC, fengtianze commented on src/form/form-item/form-item.component.scss
>            width: map-get($map, width);
width去掉。设计稿上可能没体现的一个交互，form item放对话框里如果宽度不够可以自动缩短

2021-11-11 03:11 UTC, JounQin requested changes

2021-11-11 03:11 UTC, JounQin commented on src/form/form-item/form-item.component.ts
> +  width = FormItemWidth.Medium;
用 `as const` + `ValueOf` 的方式支持纯字符串，参考 https://github.com/alauda/alauda-ui/blob/fix/fix-form-item-width/src/form/form.types.ts#L15

这里改成 `width:FormItemWidth = FormItemWidth.Medium`

2021-11-11 03:12 UTC, yinshuxun commented on src/form/form-item/form-item.component.ts
> +  width = FormItemWidth.Medium;
1

2021-11-11 03:44 UTC, JounQin commented
changeset 记得加一下

2021-11-11 07:39 UTC, JounQin approved these changes

2021-11-11 08:12 UTC, merged