Fix/search input clearable button over the long text value
alauda/alauda-ui pull request #366
Opened 2022-07-06 08:36 UTC by yangxiaolang

search-input开启clearable后，clear图标会覆盖在过长的输入内容上
#365

2022-07-06 10:21 UTC, JounQin commented
The PR title should follow the commit message style.

And Please add a changeset for it following @changeset-bot's comment.

2022-07-06 10:28 UTC, JounQin requested changes
Add a story for previewing.

2022-07-11 03:42 UTC, yangxiaolang commented
> Add a story for previewing.

bugfix for search-input , could i use exsited search-input story for preview instead of add a new story

2022-07-11 04:09 UTC, JounQin commented
> > Add a story for previewing.
> 
> bugfix for search-input , could i use exsited search-input story for preview instead of add a new story

Sure

2022-07-12 00:36 UTC, JounQin requested changes

2022-07-12 00:36 UTC, JounQin commented on .changeset/warm-planets-switch.md
> +Fix/repaire search input clear icon over the long text value and remove useless css
Align with the commit style

2022-07-15 01:45 UTC, JounQin commented on src/theme/_var.scss
> +    line-height: use-var(line-height-xl),
看起来有点奇怪

2022-07-15 02:46 UTC, yangxiaolang commented on src/theme/_var.scss
> +    line-height: use-var(line-height-xl),
这个是search-button左边框要距输入框上线边框固定4px, 咱们这是拿输入框高度 - 行高做出来的 ， 之前这种做法在 medium && small 尺寸下分别是 （32-20）/2  && （28 -20）/2 ， 其实还是需要确认下不同尺寸下输入框行高定多高
要不我撤回这个改动吧，本来这个pr就是要修文本覆盖的问题的

2022-07-15 02:57 UTC, JounQin requested changes

2022-07-15 02:57 UTC, JounQin commented on src/theme/_var.scss
> +    line-height: use-var(line-height-xl),
嗯，特殊的地方特殊覆盖即可。

2022-07-15 09:36 UTC, yangxiaolang commented
上下边框4px那个问题先不动了，只修改清空图标会覆盖输入文本的问题

2022-07-15 13:05 UTC, JounQin submitted a review, later dismissed
Good job.

2022-07-18 02:26 UTC, JounQin approved these changes

2022-07-18 02:28 UTC, merged